<?xml version="1.0"?>
<!DOCTYPE SmartRestaurant [
	<!ELEMENT SmartRestaurant (type,data+)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT language (#PCDATA)>
	<!ELEMENT data (item*)>
	<!ELEMENT item (#PCDATA)>
	<!ATTLIST item
		name (CDATA) #REQUIRED
	>
]>
<SmartRestaurant>
	<type> translation </type>
	<language>en</language>
	<data>
		<item name="ABOUT_MHR">about MHR</item>
		<item name="ACCESS_DENIED">access denied</item>
		<item name="ACCESS_DENIED_EXPLAIN">you have not the authorization required to enter this area.&amp;lt;br/&amp;gt;
Maybe you didn\&amp;#039;t authenticate yet or you authenticated without a password. In such cases, connect before trying to enter this zone, otherwise ask the administrator to give you the access.</item>
		<item name="ACCOUNT">Account</item>
		<item name="ACCOUNTING">Accounting</item>
		<item name="ACCOUNTING_DATABASE">Accounting Database</item>
		<item name="ACCOUNTING_DATABASES">Accounting Databases</item>
		<item name="ACCOUNT_ABI">ABI Code</item>
		<item name="ACCOUNT_BANK">Bank</item>
		<item name="ACCOUNT_BIC">Destination BIC code</item>
		<item name="ACCOUNT_CAB">CAB code</item>
		<item name="ACCOUNT_CIN">CIN code</item>
		<item name="ACCOUNT_CURRENCY">Currency (International code, eg. EUR, USD, etc)</item>
		<item name="ACCOUNT_EDIT">Edit Account</item>
		<item name="ACCOUNT_IBAN">IBAN code</item>
		<item name="ACCOUNT_INITIAL_AMOUNT">Initial Amount</item>
		<item name="ACCOUNT_INSERT">Insert Account</item>
		<item name="ACCOUNT_LABEL_AMOUNT">Amount</item>
		<item name="ACCOUNT_LABEL_BANK_ACCOUNT">Bank Account</item>
		<item name="ACCOUNT_LABEL_CAUSAL">Causal</item>
		<item name="ACCOUNT_LABEL_DATE">Date</item>
		<item name="ACCOUNT_LABEL_DESCRIPTION">Description</item>
		<item name="ACCOUNT_LABEL_IF_NEGATIVE">If negative</item>
		<item name="ACCOUNT_LABEL_IN">In</item>
		<item name="ACCOUNT_LABEL_OUT">Out</item>
		<item name="ACCOUNT_LEGEND">Bank Account</item>
		<item name="ACCOUNT_LIST">Accounts List</item>
		<item name="ACCOUNT_MAIN_LEGEND">Bank Accounts</item>
		<item name="ACCOUNT_MOVEMENT">The movement</item>
		<item name="ACCOUNT_MOVEMENT_ADD_SUCCESS">has been successfully added</item>
		<item name="ACCOUNT_MOVEMENT_DELETE">Delete movement</item>
		<item name="ACCOUNT_MOVEMENT_DELETE_SUCCESS">has been successfully deleted</item>
		<item name="ACCOUNT_MOVEMENT_EDIT">Edit Movement</item>
		<item name="ACCOUNT_MOVEMENT_INSERT">Insert Movement</item>
		<item name="ACCOUNT_MOVEMENT_LEGEND">Bank Account Movement</item>
		<item name="ACCOUNT_MOVEMENT_LIST">Movements list</item>
		<item name="ACCOUNT_MOVEMENT_NOTHING_DONE">Nothing has been done</item>
		<item name="ACCOUNT_MOVEMENT_UPDATE_SUCCESS">has been successfully updated</item>
		<item name="ACCOUNT_NAME">Name</item>
		<item name="ACCOUNT_NUMBER">Account number</item>
		<item name="ACCOUNT_SWIFT">Receiver BIC code (SWIFT)</item>
		<item name="ACCOUNT_TABLE_ABI">ABI</item>
		<item name="ACCOUNT_TABLE_AMOUNT">Amount</item>
		<item name="ACCOUNT_TABLE_BANK">Bank</item>
		<item name="ACCOUNT_TABLE_BIC">BIC</item>
		<item name="ACCOUNT_TABLE_CAB">CAB</item>
		<item name="ACCOUNT_TABLE_CIN">CIN</item>
		<item name="ACCOUNT_TABLE_CURRENCY">Currency</item>
		<item name="ACCOUNT_TABLE_IBAN">IBAN</item>
		<item name="ACCOUNT_TABLE_NAME">Name</item>
		<item name="ACCOUNT_TABLE_NUMBER">Number</item>
		<item name="ACCOUNT_TABLE_SWIFT">SWIFT</item>
		<item name="ACCOUNT_TABLE_TITLE">Bank Accounts</item>
		<item name="ACCOUNT_THE">The Bank Account</item>
		<item name="ACCOUNT_TITLE">Movements for the account</item>
		<item name="ACTION_IS_DEFINITIVE">This action is &amp;lt;b&amp;gt;definitive&amp;lt;/b&amp;gt;</item>
		<item name="ADD">add</item>
		<item name="ADDRESS">Address</item>
		<item name="ALL">All</item>
		<item name="ALL_TABLES">all the tables</item>
		<item name="ALREADY_CONNECTED">you are already connected</item>
		<item name="AMOUNT">Amount</item>
		<item name="ANNULL">annull record</item>
		<item name="ANNULLED">annulled</item>
		<item name="ANNULLED_ABBR">ANN</item>
		<item name="APPLY">Apply</item>
		<item name="APPLY_DISCOUNT">Apply discount</item>
		<item name="ASK_DELETE_CONFIRMATION">Do you really want to delete the order?</item>
		<item name="ASSOCIATED_INVOICE">associated invoice</item>
		<item name="ASSOCIATE_ASK">Do you want to associate this table to your ID?</item>
		<item name="ASSOCIATION">association</item>
		<item name="AUTOCALC">autocalc</item>
		<item name="AUTOCALC_LEVELS">autocalc levels</item>
		<item name="AUTOCALC_START_VALUE">starting autocalc quantity. To be used to skip some autocalc levels and start from the next ones</item>
		<item name="AVAILABLE">Available</item>
		<item name="BACK_TO_LIST">Back to the list</item>
		<item name="BACK_TO_MAIN">back to the main page</item>
		<item name="BACK_TO_TABLE">back to the table</item>
		<item name="BACK_TO_TABLES">back to tables list</item>
		<item name="BANK">Bank	</item>
		<item name="BANK_ACCOUNT">Bank Account</item>
		<item name="BANK_FILE">Bank File</item>
		<item name="BILL">bill</item>
		<item name="BILL_ANNULLED_OK">the bill has been annulled</item>
		<item name="BILL_PRINT">bill print</item>
		<item name="BILL_RESET">bill reset</item>
		<item name="CANNOT_PREPARE_DISH">cannot be prepared</item>
		<item name="CASH">Cash</item>
		<item name="CASHIER">cashier</item>
		<item name="CATEGORIES">Categories</item>
		<item name="CATEGORIES_SHOW_ALL">Show all</item>
		<item name="CATEGORY">Category</item>
		<item name="CATEGORY_COLOR">Category color</item>
		<item name="CATEGORY_PRINT">category print</item>
		<item name="CHANGELOG">Changelog</item>
		<item name="CHARSET">iso-8859-1</item>
		<item name="CHECK_COLOR">Check the color value</item>
		<item name="CHECK_COLOR_BEGIN">The color value has to begin with #</item>
		<item name="CHECK_DATABASE_FOUND">The database already exists, select another database name.</item>
		<item name="CHECK_DATABASE_NAME">Check the database name</item>
		<item name="CHECK_DATE">Check the date</item>
		<item name="CHECK_DAY">Check the day</item>
		<item name="CHECK_DESCRIPTION">Check the description</item>
		<item name="CHECK_HOUR">Check the hour</item>
		<item name="CHECK_MINUTE">Check the minutes</item>
		<item name="CHECK_MONTH">Check the month</item>
		<item name="CHECK_NAME">Check the name</item>
		<item name="CHECK_NAME_ALREADY_TAKEN">There is already an user with this name, please choose another</item>
		<item name="CHECK_NO_INVOICE_ERROR">Internal error: no invoice id supplied. Please contact</item>
		<item name="CHECK_NO_TYPE_ERROR">Internal error: no type supplied. Please contact</item>
		<item name="CHECK_NUMBER">Check the number.</item>
		<item name="CHECK_ORDER">Check the ordering number</item>
		<item name="CHECK_PASSWORD_COMPARE">check that the passwords are the same</item>
		<item name="CHECK_PASSWORD_LENGHT">check the password length. It should be at least 6 characters.</item>
		<item name="CHECK_QUANTITY">check the quantity</item>
		<item name="CHECK_SURNAME">Check the surname</item>
		<item name="CHECK_TAXABLE">Check the taxable amount.</item>
		<item name="CHECK_TEMPLATE">Check the template</item>
		<item name="CHECK_TIME_BEFORE_NOW">The time can&amp;#039;t be before now</item>
		<item name="CHECK_VALUE">check the value</item>
		<item name="CHECK_YEAR">Check the year</item>
		<item name="CHEQUE_NUMBER">Check number</item>
		<item name="CITY">City</item>
		<item name="CLEARING">table clearing</item>
		<item name="CLICK_HERE_TO_UPGRADE">click here to upgrade My Handy Restaurant</item>
		<item name="CLOSE">table close</item>
		<item name="CLOSED">closed</item>
		<item name="CLOSE_TABLE">close the table</item>
		<item name="CLOSE_TABLE_ASK">Do you want to close this table?&amp;lt;br/&amp;gt;After closing it only the cashier will be able to access it.</item>
		<item name="COME_BACK_HERE">come back here</item>
		<item name="CONFIG">configuration</item>
		<item name="CONFIGURATION">Configuration</item>
		<item name="CONNECT">Connect</item>
		<item name="CONNECTED_AS">you&amp;#039;re connected as</item>
		<item name="CONTACTS">Contacts</item>
		<item name="CONTACTS_LIST">Contacts List</item>
		<item name="CONTACT_INSERT">Insert</item>
		<item name="CONTAINED">contained</item>
		<item name="CREATE_ASSOCIATED_STOCK">create the associated stock record</item>
		<item name="CREATE_SERVICE_FEE">Insert people number</item>
		<item name="CREATION">creation</item>
		<item name="CUSTOMER">customer</item>
		<item name="CUSTOMER_DATA">customer data</item>
		<item name="DATABASE">Database</item>
		<item name="DATABASE_BACKUP">Backup</item>
		<item name="DATABASE_COMMON">Common Database</item>
		<item name="DATABASE_COMPARE">Compare</item>
		<item name="DATABASE_DELETE_WARNING">&amp;lt;b&amp;gt;Warning:&amp;lt;/b&amp;gt; If you delete the database, all the data associated to it (accounting, statistics log, addressbook, receipts log, stock movements) will be deleted and &amp;lt;b&amp;gt;unrecoverable&amp;lt;/b&amp;gt;</item>
		<item name="DATABASE_FROM">Base Database&amp;lt;br /&amp;gt;(the new version&amp;#039;s one)</item>
		<item name="DATABASE_NAME">&amp;lt;b&amp;gt;Database Name&amp;lt;/b&amp;gt;&amp;lt;br /&amp;gt;the database name as in mysql databases list</item>
		<item name="DATABASE_RESTORE">restore</item>
		<item name="DATABASE_TO">Target Database&amp;lt;br /&amp;gt;(the old version&amp;#039;s one)</item>
		<item name="DATE">date</item>
		<item name="DEBTS">debts</item>
		<item name="DEFAULT">default</item>
		<item name="DELETE">Delete</item>
		<item name="DELETE_ALL">delete all</item>
		<item name="DELETE_ALL_CONFIRM">Are you sure you want to delete ALL THE RECORDS?
This is equivalent to a total reset of this subsystem.</item>
		<item name="DELETE_DATABASE">&amp;lt;b&amp;gt;Delete the database&amp;lt;/b&amp;gt; (includes deletion of all the tables).</item>
		<item name="DELETE_DATABASE_TABLES">&amp;lt;b&amp;gt;Delete My Handy Restaurant tables&amp;lt;/b&amp;gt; from this database when deleting this record.</item>
		<item name="DELETE_NONE">No record has been deleted</item>
		<item name="DELETE_OK">Deleted successfully</item>
		<item name="DELETE_RECORD_CONFIRM">Are you sure you want to delete the following record?</item>
		<item name="DELETE_SELECTED">delete selected</item>
		<item name="DELETION">deletion</item>
		<item name="DESCRIPTION">description</item>
		<item name="DISABLED">disabled</item>
		<item name="DISCONNECTED_ERROR">Error: you\&amp;#039;ve not been disconnected.</item>
		<item name="DISCONNECTED_OK">You&amp;#039;ve been disconnected successfully.</item>
		<item name="DISCONNECTION">disconnection</item>
		<item name="DISCONNECT_ASK">Do you really want to disconnect?</item>
		<item name="DISCOUNT">Discount</item>
		<item name="DISH">Dish</item>
		<item name="DISHES">Dishes</item>
		<item name="DISHES_INGREDIENT_QUANTITIES">ingredient quantities in dishes</item>
		<item name="DISH_AUTOMATIC_CALCULATOR">Automatic price calculator (Autocalc)</item>
		<item name="DISH_AUTOMATIC_CALCULATOR_HELP">The Autocalc system calculates the price of the dish by counting the ingredients number.&amp;lt;br/&amp;gt;
You can set the prices in the Menu-&amp;gt;Autocalc page.&amp;lt;br/&amp;gt;
&amp;lt;b&amp;gt;If the Autocalc is on the price of the dish is ignored.&amp;lt;/b&amp;gt;</item>
		<item name="DISH_CODE">Code</item>
		<item name="DISH_COST">dish cost</item>
		<item name="DISH_DATA">dish data</item>
		<item name="DISH_DOES_NOT_EXIST">the dish doesn\&amp;#039;t exist</item>
		<item name="DISH_GENERIC">Generic Dish - to be used for not previewed cases, such as a very special request. Its price may be modified by the cashier.</item>
		<item name="DISH_INGREDIENT_INCLUDED">Included</item>
		<item name="DISH_INGREDIENT_NO">No</item>
		<item name="DISH_QUANTITY">dish qty</item>
		<item name="DISH_REVENUE">dish revenue</item>
		<item name="DISH_STOCK">Stock (if active, the items will be counted in the stock management)</item>
		<item name="DISSOCIATE">Dissociate from table</item>
		<item name="DISSOCIATION">dissociation</item>
		<item name="DRIVER">driver</item>
		<item name="DROP_TABLES">Adds the code used to delete (DROP) the  database tables when restoring</item>
		<item name="EDIT">edit</item>
		<item name="EDIT_CUSTOMER_DATA">edit customer data</item>
		<item name="EDIT_NONE">No record has been edited</item>
		<item name="EDIT_OK">Updated successfully</item>
		<item name="EDIT_QUANTITIES">edit quantities</item>
		<item name="EMAIL">e-mail</item>
		<item name="EMPLOYEE_FILE">employee file</item>
		<item name="EMPTY_TABLE_BUTTON">reset the table</item>
		<item name="EMPTY_TABLE_EXPLAIN">Do you want to reset orders list?&amp;lt;h4&amp;gt;If you reset it, it will be &amp;lt;b&amp;gt;unrecoverable&amp;lt;/b&amp;gt;.&amp;lt;/h4&amp;gt;</item>
		<item name="ERROR">There has been an error</item>
		<item name="ERROR_NONE_FOUND">No record has been found</item>
		<item name="ERROR_NONE_FOUND_CATEGORY">No category has been found</item>
		<item name="ERROR_NONE_FOUND_DESTINATION">No destination has been found</item>
		<item name="ERROR_NO_CATEGORY_SELECTED">No category has been selected.</item>
		<item name="ERROR_NO_DISH_SELECTED">No dish has been selected.</item>
		<item name="ERROR_NO_INGREDIENT_SELECTED">No ingredient has been selected.</item>
		<item name="ERR_201">a generic order without price is present.&amp;lt;br&amp;gt;Before going on the price has to be set by a cashier, by clicking on the order price, then it will be possible to print the bill.</item>
		<item name="ERR_400">An error has been raised by the Operative System printing service. Please see MHR error log for further info.</item>
		<item name="ERR_405">no order has been selected</item>
		<item name="ERR_601">wrong password.&amp;lt;br/&amp;gt;Please check that you typed the correct password.&amp;lt;br/&amp;gt;Remember that the passwords are case-sensitive (Upper and lower case letters are &amp;lt;b&amp;gt;not&amp;lt;/b&amp;gt; the same), so check that your caps-lock key has not been pressed.</item>
		<item name="ERR_NO_CUSTOMER_FOUND">no customer found</item>
		<item name="ERR_UNKNOWN">Unknown error</item>
		<item name="EXCLUDING_NOT_PAID_INVOICES">excluding not paid invoices</item>
		<item name="EXTRA_CARE">extra care</item>
		<item name="EXTRA_CARE_ABBR">ATT</item>
		<item name="FAILED">failed</item>
		<item name="FAX">fax</item>
		<item name="FEW">few</item>
		<item name="FILE">File</item>
		<item name="FREE">free</item>
		<item name="FROM">from</item>
		<item name="FROM_TIME">from</item>
		<item name="GENERIC">generic</item>
		<item name="GENERIC_NOT_PRICED">generic dish not priced</item>
		<item name="GENERIC_PRICE_DESCRIPTION">This is a generic dish, so the price has to be other then 0.00.</item>
		<item name="GENERIC_PRICE_INSTRUCTION">Please, insert the new total price (for all the portions of this dish) in the following text box, then click on</item>
		<item name="GLOBAL_SEARCH">global search</item>
		<item name="GO_BACK">go back</item>
		<item name="GO_MAIN_PAGE">Go to the main page</item>
		<item name="GO_MAIN_REPORT">Go to the main report</item>
		<item name="GO_ON">Go on</item>
		<item name="HIDE_NAMES">hide the names</item>
		<item name="HIDE_ORDERS">hide the orders</item>
		<item name="HIDE_TOPLIST">hide the toplist</item>
		<item name="HTML">HTML</item>
		<item name="ID">ID</item>
		<item name="IF_YOU_ARE_NOT_DISCONNECT_0">If you\&amp;#039;re not</item>
		<item name="IF_YOU_ARE_NOT_DISCONNECT_1">&amp;lt;a href=\&amp;quot;disconnect.php\&amp;quot;&amp;gt;disconnect&amp;lt;/a&amp;gt;</item>
		<item name="INCLUDED">included</item>
		<item name="INCLUDING_NOT_PAID_INVOICES">including not paid invoices</item>
		<item name="INCOME">income</item>
		<item name="INCOME_COLLAPSE">Collapse incomes</item>
		<item name="INCOME_EXPAND">Expand incomes</item>
		<item name="INCOMINGS">income</item>
		<item name="INGREDIENT">Ingredient</item>
		<item name="INGREDIENTS">Ingredients</item>
		<item name="INGREDIENT_CODE">Code</item>
		<item name="INGREDIENT_OVERRIDE_AUTOCALC">Disable Autocalc</item>
		<item name="INGREDIENT_OVERRIDE_AUTOCALC_HELP">If you disable Autocalc for this ingredient, the price of the ingredient will be used anyway.&amp;lt;br/&amp;gt;
Furthermore the Autocalc system will not count this ingredient when calculating the price.&amp;lt;br&amp;gt;
You should use this option if you want the price of the ingredient to be always 0.</item>
		<item name="INGREDIENT_QUANTITIES">ingredients quantities</item>
		<item name="INSERT">Insert</item>
		<item name="INSERT_CUSTOMER_DATA">insert customer data</item>
		<item name="INSERT_NEW">New record</item>
		<item name="INSERT_PRIORITY">You have to insert priority.</item>
		<item name="INTERNAL_RECEIPT_ID">internal ID</item>
		<item name="INVOICE">invoice</item>
		<item name="INVOICE_ANNULLED_OK">the invoice has been annulled</item>
		<item name="ITEM">item</item>
		<item name="LANGUAGE">Language</item>
		<item name="LASTS">last</item>
		<item name="LAST_OPERATION">Last operation</item>
		<item name="LAST_UPGRADE_DONE">last successful upgrade</item>
		<item name="LIMITING_INGREDIENT">limiting ingredient</item>
		<item name="LOGIN">Login</item>
		<item name="LOGOUT">Logout</item>
		<item name="LOT">a lot</item>
		<item name="MAIN">Main</item>
		<item name="MENU">Menu</item>
		<item name="MENU_EDITING">Menu editing</item>
		<item name="MHR_ONLINE_HELP">MHR Online Help</item>
		<item name="MHR_TABLES_ONLY">read only the tables of My Handy Restaurant and ignore the others</item>
		<item name="MINUS">minus</item>
		<item name="MOBILE">Mobile</item>
		<item name="MODS_SETTING">mods setting</item>
		<item name="MONEY">money</item>
		<item name="MOVEMENT">movement</item>
		<item name="MOVE_TABLE">Move the table</item>
		<item name="MYSQLDUMP_FORMAT">Use &amp;#039;complete&amp;#039; and &amp;#039;extended&amp;#039; output format (smaller output file)</item>
		<item name="MYSQL_VERSION">MySQL server version</item>
		<item name="MY_TABLES">My tables</item>
		<item name="NAME">name</item>
		<item name="NAME_INTERNAL_DATABASE">&amp;lt;b&amp;gt;Internal Name&amp;lt;/b&amp;gt;&amp;lt;br /&amp;gt;used when displaying the name to users</item>
		<item name="NAME_PRINTER">&amp;lt;b&amp;gt;Internal name&amp;lt;/b&amp;gt;&amp;lt;br/&amp;gt;used only to set where to print dishes in the dishes list</item>
		<item name="NO">No</item>
		<item name="NONE">none</item>
		<item name="NOTE">note</item>
		<item name="NOT_PAID_BUTTON">Write Not Paid</item>
		<item name="NOW_SHOWING_RECORDS">records</item>
		<item name="NO_INGREDIENT_QUANTITY_INSERTED">no ingredient quantity inserted</item>
		<item name="NO_RECORD_SELECTED">No record has been selected</item>
		<item name="NO_STOCK_MOVEMENT_ASSOCIATED">no stock movement is associated to the invoice</item>
		<item name="NO_TABLE_FOUND">No table has been found</item>
		<item name="NO_UPGRADE_IS_AVAILABLE">no upgrade is available.&amp;lt;br/&amp;gt;Probably you already upgraded to the most recent database version.</item>
		<item name="NUMBER_ABBR">n</item>
		<item name="NUM_RECORDS_FOUND">records found</item>
		<item name="OBJECT">object</item>
		<item name="OBJECT_ID">object ID</item>
		<item name="OF_DAY">of</item>
		<item name="OPEN">open</item>
		<item name="OR">or</item>
		<item name="ORDER">order</item>
		<item name="ORDERS_PRINT">orders print</item>
		<item name="ORDER_PRINTED_AT">Order printed at</item>
		<item name="ORDER_PRINTED_MINS_AGO">minutes ago</item>
		<item name="ORDER_PRINTED_MINS_AGO_ABBR">mins</item>
		<item name="OUTPUT_TYPE">Output type</item>
		<item name="PAID">paid</item>
		<item name="PAID_ALREADY">The table already paid.</item>
		<item name="PAID_ASK">has the table paid?</item>
		<item name="PAID_BUTTON">write paid</item>
		<item name="PASSWORD">password</item>
		<item name="PASSWORD_CONFIRM">password check</item>
		<item name="PASSWORD_NOT_SET">the password is not set</item>
		<item name="PASSWORD_REMOVE">remove the password</item>
		<item name="PASSWORD_SET">the password is set</item>
		<item name="PAYMENT">payment</item>
		<item name="PEOPLE">people</item>
		<item name="PERCENTUAL">Percentual</item>
		<item name="PERCENT_INSERTED">percent inserted</item>
		<item name="PERIOD">period</item>
		<item name="PERMISSIONS">permessi</item>
		<item name="PHONE">Phone</item>
		<item name="PHP_VERSION">PHP version</item>
		<item name="PIECE">piece</item>
		<item name="PLACE">place</item>
		<item name="PLUS">plus</item>
		<item name="POSSIBLE_QUANTITY">possible quantity</item>
		<item name="PRICE">Price</item>
		<item name="PRINT">Print</item>
		<item name="PRINTABLE_VERSION">printable version</item>
		<item name="PRINTER">Printer</item>
		<item name="PRINTERS">Printers</item>
		<item name="PRINTERS_LIST">List</item>
		<item name="PRINTERS_TEST">Test page</item>
		<item name="PRINTERS_TEST_SEND">Send test page to all printers</item>
		<item name="PRINTER_BILL">&amp;lt;b&amp;gt;Bills printer&amp;lt;/b&amp;gt; - Print bills on this printer</item>
		<item name="PRINTER_DESTINATION">&amp;lt;b&amp;gt;Printing queue name&amp;lt;/b&amp;gt;&amp;lt;br&amp;gt;the name of the printing queue&amp;lt;br&amp;gt;(name previously defined in the external printing system)</item>
		<item name="PRINTER_DRIVER">&amp;lt;b&amp;gt;Internal driver name&amp;lt;/b&amp;gt;&amp;lt;br/&amp;gt;the internal driver to be used to get command codes</item>
		<item name="PRINTER_INTERNAL_NAME">Internal name</item>
		<item name="PRINTER_INVOICE">&amp;lt;b&amp;gt;Invoices printer&amp;lt;/b&amp;gt; - Print invoices on this printer</item>
		<item name="PRINTER_LANGUAGE">&amp;lt;b&amp;gt;Printer language&amp;lt;/b&amp;gt;&amp;lt;br/&amp;gt;The language in which the tickets should be printed&amp;lt;br&amp;gt;(experimental)</item>
		<item name="PRINTER_RECEIPT">&amp;lt;b&amp;gt;Receipts printer&amp;lt;/b&amp;gt; - Print receipts on this printer</item>
		<item name="PRINTER_TEMPLATE">&amp;lt;b&amp;gt;Templates directory&amp;lt;/b&amp;gt;&amp;lt;br&amp;gt;directory containing the set of printing templates to be used for printing</item>
		<item name="PRINTER_TEST_PAGE">Test page</item>
		<item name="PRINTER_TEST_PAGE_END">Test page end</item>
		<item name="PRINTER_TEST_SENT">Test page sent to printers</item>
		<item name="PRINTING_DRIVER">printing driver</item>
		<item name="PRINTING_QUEUE">printing queue</item>
		<item name="PRINTING_TEMPLATE">printing template</item>
		<item name="PRINTS_ATTENTION">ATTENTION</item>
		<item name="PRINTS_BILL">bill</item>
		<item name="PRINTS_DELETED">Deleted</item>
		<item name="PRINTS_DISCOUNT">discount</item>
		<item name="PRINTS_FEW">FEW</item>
		<item name="PRINTS_GO_NOW">go now</item>
		<item name="PRINTS_GO_WITH">go with</item>
		<item name="PRINTS_INVOICE">invoice</item>
		<item name="PRINTS_LOT">A LOT</item>
		<item name="PRINTS_NUMBER_ABBR">n.</item>
		<item name="PRINTS_PEOPLE">people</item>
		<item name="PRINTS_PRIORITY">priority</item>
		<item name="PRINTS_RECEIPT">receipt</item>
		<item name="PRINTS_TABLE">table</item>
		<item name="PRINTS_TAKEAWAY">takeaway</item>
		<item name="PRINTS_TAX">tax</item>
		<item name="PRINTS_TAXABLE">taxable</item>
		<item name="PRINTS_TAX_TOTAL">total tax</item>
		<item name="PRINTS_TOTAL">total</item>
		<item name="PRINTS_WAIT">WAIT</item>
		<item name="PRINTS_WAITER">waiter</item>
		<item name="PRINT_BILL">print bill</item>
		<item name="PRINT_BILL_EXPLAIN">&amp;lt;b&amp;gt;Print bills&amp;lt;/b&amp;gt; - on if you want receipts/bill/invoices assigned to this database to be printed</item>
		<item name="PRINT_DESTINATION">Print destination</item>
		<item name="PRINT_GO_2">go with 2nd priority orders</item>
		<item name="PRINT_GO_3">go with last priority orders</item>
		<item name="PRINT_ORDERS">print orders</item>
		<item name="PRINT_SEPARATED_BILLS">print separated bills</item>
		<item name="PRIORITY">priority</item>
		<item name="PRIORITY_ABBR">p</item>
		<item name="PRIORITY_DEFAULT">suggested priority - set to none to give no suggestion</item>
		<item name="QUANTITY">quantity</item>
		<item name="QUANTITY_ABBR">q.ty</item>
		<item name="QUANTITY_AUTOCALC_EXPLAIN">Quantity&amp;lt;br/&amp;gt;
The price of the modifications will be the one set here when this quantity is reached.&amp;lt;br/&amp;gt;
Set this to default to price beyond the maximum quantity considered.</item>
		<item name="QUANTITY_TO_MODIFY">quantity to modify</item>
		<item name="QUANTITY_UPDATE">quantity update</item>
		<item name="QUEUE">queue</item>
		<item name="RECEIPT">receipt</item>
		<item name="RECEIPT_ANNULLED_OK">the receipt has been annulled</item>
		<item name="RECONNECT_WITH_PASSWORD">Reconnect with password</item>
		<item name="RECORDS">records</item>
		<item name="REDIRECTED_FOR_UPGRADE_EXPLAIN">You have been redirected here because an upgrade is available. You should upgrade your version of My Handy Restaurant before going on.</item>
		<item name="REMOVE">Remove</item>
		<item name="REMOVE_CUSTOMER_DATA">remove customer data</item>
		<item name="REMOVE_DEFINITIVE">Remove (definitive)</item>
		<item name="REOPEN">reopening</item>
		<item name="REOPEN_TABLE">Re-open the table</item>
		<item name="REOPEN_TABLE_ASK">Do you want to reopen this table?&amp;lt;br/&amp;gt;&amp;lt;h4&amp;gt;After reopening it anybody could acces and modify it!&amp;lt;/h4&amp;gt;</item>
		<item name="REPORTS">Reports</item>
		<item name="REPORT_GENERATE">Generate the report</item>
		<item name="RESET_SEPARATED">reset separated bills counter</item>
		<item name="RESET_SEPARATED_EXPLAIN">Are you sure to reset the separated bills counter?&amp;lt;br/&amp;gt;
If you do it &amp;lt;b&amp;gt;all&amp;lt;/b&amp;gt; the separated bills will be reprinted.&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
The use of this function is suggested &amp;lt;b&amp;gt;only&amp;lt;/b&amp;gt; if you\&amp;#039;re having problems with separated orders.&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
To proceed, check the \&amp;#039;Reset separated bills\&amp;#039; checkbox and click on the \&amp;#039;OK\&amp;#039; image on the upper right corner.</item>
		<item name="RESTORE_DB">database on which the restore should be applied</item>
		<item name="RESTORE_FILE">restore file</item>
		<item name="RESTORE_OK">restore completed successfully</item>
		<item name="RESTORE_WARNING">&amp;lt;b&amp;gt;Warning:&amp;lt;/b&amp;gt; Restoring the database is a dangerous operation.&amp;lt;br/&amp;gt;
It may delete all the data that is in the database now.&amp;lt;br/&amp;gt;
You will lose all the data added to the database since the creation of the backup file you will restore.&amp;lt;br/&amp;gt;
You are &amp;lt;b&amp;gt;strongly&amp;lt;/b&amp;gt; suggested to &amp;lt;a href=\&amp;quot;../admin/export_db.php?command=none\&amp;quot;&amp;gt;make a backup&amp;lt;/a&amp;gt; of the actual database before going on.</item>
		<item name="SEARCH">search</item>
		<item name="SEARCH_IN">search in</item>
		<item name="SEARCH_RESULTS">search results</item>
		<item name="SEARCH_TERM_TOO_SHORT">the search term is too short. Try with a longer word.</item>
		<item name="SECONDS">seconds</item>
		<item name="SECONDS_TO_GENERATE_THE_PAGE">seconds to generate the page</item>
		<item name="SELECT_ALL">select all</item>
		<item name="SEND_TO_STOCK">send to stock</item>
		<item name="SEPARATED_BILLS">separated bills</item>
		<item name="SERVICE_FEE">service fee</item>
		<item name="SET_DEFAULT">set default</item>
		<item name="SET_TAKEAWAY_SURNAME_FIRST">you must choose the customer before printing the orders.</item>
		<item name="SHOW_NAMES">show the names</item>
		<item name="SHOW_ORDERS">show the orders</item>
		<item name="SHOW_TOPLIST">show the toplist</item>
		<item name="SIMULATE_ONLY">Simulate only (doesn&amp;#039;t modify the database)</item>
		<item name="SIMULATION_ACTIVE">Simulation mode&amp;lt;br/&amp;gt;(database has not been modified)</item>
		<item name="SOCIAL_SECURITY_NUMBER">social security number</item>
		<item name="STATISTICS">statistics</item>
		<item name="STATS_TOTAL_WAITERS">Total revenue per waiter</item>
		<item name="STOCK">Stock</item>
		<item name="STOCK_INSERT_INGREDS_QUANTITIES">insert ingredient quantites</item>
		<item name="STOCK_MOVEMENT">stock movement</item>
		<item name="STOCK_MOVEMENTS">stock movements</item>
		<item name="STOCK_SITUATION">stock situation</item>
		<item name="STOCK_SYNC_ALL_DISHES">syncronize all the dishes</item>
		<item name="STOCK_SYNC_ALL_INGREDS">syncronize all the ingredients</item>
		<item name="STOCK_UPDATE_ERROR">error updating the stock data</item>
		<item name="STOCK_UPDATE_OK">stock successfully updated</item>
		<item name="STRUCTURE_ONLY">Structure only</item>
		<item name="SUBMIT">Submit</item>
		<item name="SUBSTITUTE">Substitute</item>
		<item name="SUBSTITUTE_ASK">are you sure you want to delete this order and create a new one?</item>
		<item name="SUPPLIER_FILE">supplier file</item>
		<item name="SURNAME">Surname</item>
		<item name="SUSPEND_PRINT">suspend print</item>
		<item name="SYSTEM">System</item>
		<item name="TABLE">table</item>
		<item name="TABLES">Tables</item>
		<item name="TABLE_ALREADY_IN_USE_ERROR">Table is in use by another waiter. Retry in</item>
		<item name="TABLE_HAS_BEEN_CLEARED">The table has been cleared</item>
		<item name="TABLE_NUMBER">table number</item>
		<item name="TABLE_ORDER">Ordering number of the table in the waiters&amp;#039; tables list</item>
		<item name="TABLE_TOTAL_DISCOUNTED">Table total (discounted)</item>
		<item name="TAKEAWAY">takeaway</item>
		<item name="TAKEAWAY_DATA">takeaway data</item>
		<item name="TAKEAWAY_TABLES">takeaway tables</item>
		<item name="TAXABLE">taxable</item>
		<item name="TAXES">taxes</item>
		<item name="TAX_TO_PAY">for the selected period, the taxes you should pay are</item>
		<item name="TEMPLATE">template</item>
		<item name="TESTING">testing</item>
		<item name="TEXT">Text</item>
		<item name="TIME">time</item>
		<item name="TO">to</item>
		<item name="TOPLIST">top list</item>
		<item name="TOTAL">total</item>